erro que deu após rodar o npm run test:e2e na pasta web:
PS C:\Users\48353936860\Documents\Testes\unit-tests-starter\web> npm run test:e2e

> web@1.0.0 test:e2e
> playwright test

file:///C:/Users/48353936860/Documents/Testes/unit-tests-starter/web/playwright.config.js:1
import { defineConfig, device } from "@playwright/test";
                       ^^^^^^
SyntaxError: The requested module '@playwright/test' does not provide an export named 'device'
    at ModuleJob.#asyncInstantiate (node:internal/modules/esm/module_job:302:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:405:5)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:660:26)
    at requireOrImport (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\common\index.js:1081:12)
    at loadUserConfig (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\common\index.js:1268:46)
    at loadConfig (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\common\index.js:1275:22)
    at Object.loadConfigFromFile (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\common\index.js:1490:10)
    at runTests (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\cli\testActions.js:46:18)
    at _Command.<anonymous> (C:\Users\48353936860\Documents\Testes\unit-tests-starter\web\node_modules\playwright\lib\program.js:55:7)